name = "wedding-gallery-pages"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

services = [
  { binding = "VIEWER_WORKER", service = "viewer" },
  { binding = "VIDEO_WORKER", service = "video-streaming" }
]
